# PORTS
# REST API - 3000 - 3999
# Apollo API - 4000 - 4999
# Apollo Subscription - 5000 - 5999
# Frontends - 6000 - 6999
# postgresql - 5433
# redis - 6380

version: '3'
services:
  postgresql:
    build: ./Postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env

  redis:
    build: ./Redis
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env

  rest_auth:
    build: ./REST Auth
    ports:
      - "${REST_AUTH_PORT}:3000"
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./Rest Auth:/usr/app
    command: ["npm", "run", "dev"]

  apollo_api:
    build: ./Apollo API
    ports:
      - "${APOLLO_API_PORT}:4000"
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./Apollo API:/usr/app
    command: ["npm", "run", "dev"]

  apollo_sub:
    build: ./Apollo Subscriptions
    ports:
      - "${APOLLO_SUBSCRIPTIONS_PORT}:5000"
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./Apollo Subscriptions:/usr/app
    command: ["npm", "run", "dev"]

  web_front:
    build: ./Web Front
    ports:
      - "${WEB_FRONT_PORT}:6000"
    env_file:
      - .env
    volumes:
      - /usr/app/node_modules
      - ./Web Front:/usr/app