FROM node:10-alpine as builder
WORKDIR /usr/app
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.15
#COPY --from=builder /usr/app/nginx/default.conf /etc/nginx/conf.d/default.conf
#COPY --from=builder /usr/app/build /usr/share/nginx/html
EXPOSE 6000